services:
  leaderboard:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: leaderboard
      DATABASE_USER: leaderboard
      DATABASE_PASSWORD: leaderboard
      SERVER_ADDRESS: ":80"
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
      - traefik.http.routers.leaderboard.rule=Host(`leaderboard.thw-oswe.de`)
      - traefik.http.routers.leaderboard.tls=true
      - traefik.http.routers.leaderboard.tls.certresolver=sample
      - traefik.http.routers.leaderboard.entrypoints=http,https
    networks:
      - traefik

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: leaderboard
      MYSQL_DATABASE: leaderboard
      MYSQL_USER: leaderboard
      MYSQL_PASSWORD: leaderboard
    volumes:
      - ./migrations/1689036093_create_competitor_table.up.sql:/docker-entrypoint-initdb.d/1689036093_create_competitor_table.up.sql:ro
      - leaderboard-mysql:/var/lib/mysql:rw
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  leaderboard-mysql:
    external: true
