version: '3.7'

services:
  leaderboard:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: leaderboard
      DATABASE_USER: leaderboard
      DATABASE_PASSWORD: leaderboard
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
      - "traefik.http.middlewares.leaderboard.basicauth.users=thwoswe:$$2y$$05$$2vfMd8LM/adQ72EaAydQ/OkMnVMpCSOL24cIogReCocuLRvWOCYRe"
      - traefik.http.routers.leaderboard.middlewares=leaderboard
      - traefik.http.routers.leaderboard.rule=Host(`leaderboard.thw-oswe.de`)
      - traefik.http.routers.leaderboard.tls=true
      - traefik.http.routers.leaderboard.tls.certresolver=sample
      - traefik.http.routers.leaderboard.entrypoints=http,https

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: leaderboard
      MYSQL_DATABASE: leaderboard
      MYSQL_USER: leaderboard
      MYSQL_PASSWORD: leaderboard
    volumes:
      - ./migrations/1689036093_create_competitor_table.up.sql:/docker-entrypoint-initdb.d/1689036093_create_competitor_table.up.sql:ro